### ISSUE TITLE
How to produce the PLS_gene_predictor_vars.csv file using my own parcellation atlas,such as AAL template?

### ISSUE THREAD

**Issue by xuqiang9042** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#10]
How to produce the PLS_gene_predictor_vars.csv file using my own parcellation atlas,such as AAL template?Can you provide your script?

**Comment by KirstieJane** [comment]
Hi @xuqiang9042 - so sorry for the slow reply.

This code isn't openly available but you're welcome to contact Petra Vertes directly at pv226 AT cam DOT ac DOT uk :smile:
