### ISSUE TITLE
Code amendment for data

### ISSUE THREAD

**Issue by docni** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#3]
Hi Kirstie, 

I was wondering how to amend the code just to analyze one .csv file with cortical thickness data instead of the multiple files in the data folder ?

Thanks 

Peter

**Comment by KirstieJane** [comment]
Hi @docni - just a little note to say thank you for your question and I'll get back to you on Monday when I'm on my computer (rather than my phone).

(It's easy to do though! I just need to write you a little piece of documentation on where to find the bits of code you're looking for!)

**Comment by docni** [comment]
Thanks Kirstie and thanks for making everything available. I am very excited about implementing your analysis with my data.

bw

Peter

**Comment by KirstieJane** [comment]
Hi @docni and @cpaulaldla.

Here's a function that takes a few input files and creates correlation matrices: [WRAPPERS/corrmat_from_regionalmeasures.py](https://github.com/KirstieJane/NSPN_WhitakerVertes_PNAS2016/blob/master/WRAPPERS/corrmat_from_regionalmeasures.py).

You can covary for any number of measures so long as they're in the regional measures file.

Sorry I was slow on making this - I had a really crummy way of correcting for covariates originally that was FINE but super slow to run. This version is much faster :smile:

Please do let me know if it works for you!

**Comment by docni** [comment]
Thanks so much Kirstie!

I'll give it a go.

bw

Peter

**Comment by KirstieJane** [comment]
Me again @docni and @cpaulaldla.

I made a little wiki page with the help text for the two wrappers: https://github.com/KirstieJane/NSPN_WhitakerVertes_PNAS2016/wiki/Wrappers-help.

I'm going to close this issue now, but do let me know if you have any questions. You're my very first alpha users of the code (except for myself!) so all feedback is greatly appreciated!
