### ISSUE TITLE
How to get this on a different parcellation

### ISSUE THREAD

**Issue by ghost** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#7]
Hi Kristie,

We have been coordinating through email. however i thought this question will be more useful here.

We are trying to use your method but on a different parcellation, I see that you have the PLS_gene_predictor_vars.csv with each gene having a value for your 308 regions. 

How were you able to organise the AIBS gene data to your parcellation? if this is already documented, apologies, I was unable to find that in your repository, could you please direct towards your method for that.

**Comment by KirstieJane** [comment]
Hi @moosahmed - sorry I didn't get back to you on GitHub but thank you for your emails! I'm going to close this issue as we got it sorted out but I'm not able to make some of the responses from my collaborators publicly available 😭 . Glad it worked out in the end!
