### ISSUE TITLE
Testing 1st component for oligo genes

### ISSUE THREAD

**Issue by docni** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#8]
Hi Kirstie,

I am keen to test if my first component from the PLS is enriched for the oligo gene list you used in your paper. 

I have tried to use PLS_candidate_genes.m, I input my 1st component gene weights but I wanted to check about the oligo gene file, is the second column taken from the 1st component gene weights file (2nd column)?

What does the output file represent and how do i interpret it to find if my first component is enriched for the oligo genes (i.e. p-value)?

And just to check - for PLS1 gene weights file is the 2 column the rank and 3rd column the weight results from the PLS analysis?

Sorry for all the questions and thank you so so much for all the help you've given me!

bw

Peter

**Comment by docni** [comment]
Hi Kirstie,

Apologies for the multiple emails.

I think I have managed to figure out the PLS_candidate_genes.m script.

Could I ask under what circumstances should true and false be used (i.e taking the absolute values), as the options give quite different answers ?

Thanks 

Peter

**Comment by KirstieJane** [comment]
Hi @docni - So sorry I've been abandoning you! I'm traveling a whole bunch!

I'm glad you figured out the PLS_candidate_genes.m code.

I can't answer whether you should use True or False for the absolute values option - it entirely depends on whether you think the sign on the zscore matters.

You can [see that in our paper](https://github.com/KirstieJane/NSPN_WhitakerVertes_PNAS2016/blob/master/SCRIPTS/call_pls.py#L122) we chose **_false**_ for the direction of the oligodendrocyte gene expression meaning we did care about the sign, but **_true**_ for the direction of the schizophrenia genes meaning we didn't care about the sign.

We interpreted the oligodendrocyte gene expression as being important only if it were _higher_ in certain areas, but schizophrenia gene expression if it were either _higher_ **or** _lower_ in certain regions.

**Comment by docni** [comment]
Hi Kirstie, 

That makes sense, thanks again for all your help.

bw

Peter
