### ISSUE TITLE
How to partition a DK cortical atlas into 308 areas with equal areas(500mm2)?

### ISSUE THREAD

**Issue by xuqiang9042** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#9]
Can you povide us a script to do this step on our own imaging data?

**Comment by KirstieJane** [comment]
Hi @xuqiang9042 - I'm sorry for the slow reply!

You can use the parcellation that we used - the appropriate `.annot` files are in the [`FS_SUBJECTS/fsaverageSubP/label`](https://github.com/KirstieJane/NSPN_WhitakerVertes_PNAS2016/tree/master/FS_SUBJECTS/fsaverageSubP/label) folder as `lh.500.aparc.annot` and `rh.500.aparc.annot`. You'll need to use the freesurfer command `mri_surf2surf` to transform them to your own subject's space.

I do have code for this but I don't have it properly commented etc so I haven't released it yet. Hopefully it'll be out by the spring with a different paper. It's just a wrapper around that freesurfer command though so I'm sure you can figure it out.

If you need to make your own parcellation (eg: if you want different numbers of regions etc) you can reach out to [Dr Rafael Romero-Garcia](http://www.neuroscience.cam.ac.uk/directory/profile.php?rr480) who wrote the code. I checked with him and he's very happy to help out (but unfortunately the code is not licensed to be made openly available 😢 )

I hope that helps! Sorry again for the slow reply!

**Comment by xuqiang9042** [comment]
Thanks,Kirstie!Another question is why you partition the cortical surface into 308?why not use the original DK 34 per hemisphere atlas?You did not povide the details about it in your pnas paper.

**Comment by KirstieJane** [comment]
Hi @xuqiang9042 - we wanted all the regions to have the same surface area. It's a little important for structural network analyses but very important for functional networks (eg this paper in the same cohort: [DOI: 10.1098/rstb.2015.0362](https://doi.org/10.1098/rstb.2015.0362)) and future work will bring the different measurements together. The 308 number is the outcome of setting the minimum surface area for each region to 500mm^2.

**Comment by pikachoo03** [comment]
> Hi @xuqiang9042 - we wanted all the regions to have the same surface area. It's a little important for structural network analyses but very important for functional networks (eg this paper in the same cohort: [DOI: 10.1098/rstb.2015.0362](https://doi.org/10.1098/rstb.2015.0362)) and future work will bring the different measurements together. The 308 number is the outcome of setting the minimum surface area for each region to 500mm^2.

Hi, i would highly appreciate it if you could share the DK atlas with 308 regions
